_commit: v1.1.0
_src_path: gh:mopidy/mopidy-ext-template
author_email: git@matthewgamble.net
author_full_name: Matthew Gamble
repo_name: mopidy-api-explorer
dist_name: Mopidy-API-Explorer
ext_name: api_explorer
github_username: mopidy
short_description: Mopidy extension which lets you explore the JSON-RPC API
