_commit: v2.2.0
_src_path: gh:mopidy/mopidy-ext-template
author_email: git@matthewgamble.net
author_full_name: Matthew Gamble
dist_name: mopidy-api-explorer
ext_name: api_explorer
github_username: mopidy
short_description: Mopidy extension which lets you explore the JSON-RPC API
